---
- name: create snippets
  template: >
    src={{ item }}.py.j2
    dest=/tmp/{{ item }}.py
  with_items: "{{ edxapp_db_tune__snippets }}"

- name: run snippets
  shell: "{{ COMMON_BIN_DIR |default('/edx/bin') }}/edxapp-shell-lms </tmp/{{ item }}.py"
  with_items: "{{ edxapp_db_tune__snippets }}"

- name: remove snippets
  file: >
    state=absent
    path=/tmp/{{ item }}.py
  with_items: "{{ edxapp_db_tune__snippets }}"
